.TH POOLCOUNTERD "1" "September 2018" "PoolCounter" "User Commands"
.SH NAME
poolcounterd \- network daemon which provides mutex-like functionality
.SH SYNOPSIS
\fBpoolcounterd\fR [\-l \fIaddress\fR]
.SH OPTIONS
.TP
\fB\-l\fR \fIaddress\fR
Address to listen on. By default poolcounterd will only listen on localhost.
.SH SEE ALSO
See <https://www.mediawiki.org/wiki/PoolCounter> for documentation on the wire
protocol used by poolcounterd.
.SH LICENSE
PoolCounter is distributed under the GPL v3 or any later version, at your
option.
.SH AUTHOR
Platonides <platonides@gmail.com>
